version: '3'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: startupmetrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
